<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Content.Goobstation.UIKit</RootNamespace>
    </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Content.ModuleManager\Content.ModuleManager.csproj" />
    <ProjectReference Include="..\Content.Shared\Content.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all"/>
  </ItemGroup>

  <Import Project="..\RobustToolbox\MSBuild\Robust.Properties.targets" />
  <Import Project="..\RobustToolbox\MSBuild\XamlIL.targets" />

  <Import Project="..\RobustToolbox\Imports\Lidgren.props" />
  <Import Project="..\RobustToolbox\Imports\Client.props" />
  <Import Project="..\RobustToolbox\Imports\Shared.props" />
</Project>
