// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Starlight.MassDriver;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Starlight.MassDriver.UI;

[GenerateTypedNameReferences]
public sealed partial class MassDriverConsoleMenu : FancyWindow
{
    public event Action? OnLaunchButtonPressed;
    public event Action<MassDriverMode>? OnModeButtonPressed;
    public event Action<float>? OnThrowSpeed;
    public event Action<float>? OnThrowDistance;

    private bool _updatingState;

    public MassDriverConsoleMenu()
    {
        RobustXamlLoader.Load(this);

        var modeGroup = new ButtonGroup(false);
        AutoModeButton.Group = modeGroup;
        ManualModeButton.Group = modeGroup;

        LaunchButton.OnPressed += _ => OnLaunchButtonPressed?.Invoke();

        AutoModeButton.OnPressed += _ =>
        {
            LaunchButton.Disabled = true;
            OnModeButtonPressed?.Invoke(MassDriverMode.Auto);
        };

        ManualModeButton.OnPressed += _ =>
        {
            LaunchButton.Disabled = false;
            OnModeButtonPressed?.Invoke(MassDriverMode.Manual);
        };

        ThrowDistanceSlider.OnValueChanged += _ =>
        {
            if (_updatingState)
                return;

            var throwDistance = Normalize(ThrowDistanceSlider.Value);
            ThrowDistanceCurrentValue.Text = FormatDistance(throwDistance);
        };
        ThrowDistanceSlider.OnReleased += _ =>
        {
            if (_updatingState)
                return;

            var throwDistance = Normalize(ThrowDistanceSlider.Value);
            ThrowDistanceSlider.SetValueWithoutEvent(throwDistance);
            ThrowDistanceCurrentValue.Text = FormatDistance(throwDistance);
            OnThrowDistance?.Invoke(throwDistance);
        };

        ThrowSpeedSlider.OnValueChanged += _ =>
        {
            if (_updatingState)
                return;

            var throwSpeed = Normalize(ThrowSpeedSlider.Value);
            ThrowSpeedCurrentValue.Text = FormatSpeed(throwSpeed);
        };
        ThrowSpeedSlider.OnReleased += _ =>
        {
            if (_updatingState)
                return;

            var throwSpeed = Normalize(ThrowSpeedSlider.Value);
            ThrowSpeedSlider.SetValueWithoutEvent(throwSpeed);
            ThrowSpeedCurrentValue.Text = FormatSpeed(throwSpeed);
            OnThrowSpeed?.Invoke(throwSpeed);
        };
    }

    public void UpdateState(MassDriverComponentState state)
    {
        _updatingState = true;

        if (state.Console != null)
        {
            DisabledPanel.Visible = false;
            DisabledPanel.MouseFilter = MouseFilterMode.Ignore;
        }
        else
        {
            DisabledPanel.Visible = true;
            DisabledPanel.MouseFilter = MouseFilterMode.Stop;

            if (DisabledLabel.GetMessage() is null)
            {
                var text = new FormattedMessage();
                text.AddMarkupOrThrow(Loc.GetString("mass-driver-ui-link"));
                DisabledLabel.SetMessage(text);
            }
        }

        if (state.CurrentMassDriverMode == MassDriverMode.Auto)
        {
            AutoModeButton.Pressed = true;
            LaunchButton.Disabled = true;
        }
        else
        {
            ManualModeButton.Pressed = true;
            LaunchButton.Disabled = false;
        }

        ThrowDistanceMaxValue.Text = state.MaxThrowDistance.ToString();
        ThrowDistanceMinValue.Text = state.MinThrowDistance.ToString();
        ThrowSpeedMaxValue.Text = state.MaxThrowSpeed.ToString();
        ThrowSpeedMinValue.Text = state.MinThrowSpeed.ToString();

        ThrowDistanceSlider.MaxValue = state.MaxThrowDistance;
        ThrowDistanceSlider.MinValue = state.MinThrowDistance;
        if (!ThrowDistanceSlider.Grabbed)
        {
            ThrowDistanceSlider.SetValueWithoutEvent(state.CurrentThrowDistance);
            ThrowDistanceCurrentValue.Text = FormatDistance(state.CurrentThrowDistance);
        }

        ThrowSpeedSlider.MaxValue = state.MaxThrowSpeed;
        ThrowSpeedSlider.MinValue = state.MinThrowSpeed;
        if (!ThrowSpeedSlider.Grabbed)
        {
            ThrowSpeedSlider.SetValueWithoutEvent(state.CurrentThrowSpeed);
            ThrowSpeedCurrentValue.Text = FormatSpeed(state.CurrentThrowSpeed);
        }

        _updatingState = false;
    }

    private static float Normalize(float value, int decimals = 1)
    {
        return (float) Math.Round(value, decimals, MidpointRounding.AwayFromZero);
    }

    private static string FormatDistance(float value)
    {
        return $"{value} {Loc.GetString("mass-driver-ui-units-distance")}";
    }

    private static string FormatSpeed(float value)
    {
        return $"{value} {Loc.GetString("mass-driver-ui-units-speed")}";
    }
}
