// SPDX-FileCopyrightText: 2026 Space Station 14 Contributors
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using System.Numerics;
using System.Reflection;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Ame.Components;
using Content.Shared.Canvas;
using Content.Shared.Crayon;
using Content.Shared.Decals;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Content.Shared.Canvas.SharedCanvasComponent;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Canvas.Ui
{
    [GenerateTypedNameReferences]
    public sealed partial class CanvasWindow : FancyWindow
    {
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        private readonly SpriteSystem _spriteSystem;

        private NetEntity? _trackedEntity;
        private Texture? _blipTexture;

        private EntityUid? _owner = null;
        private CanvasUiKey _currentUiKey;

        private const int ButtonGridSize = 3;
        private int _height = 16;
        private int _width = 16;

        private string _paintingCode = string.Empty;

        // Cached, mutable view of _paintingCode used while drawing so we don't have to
        // Split/Join the whole (potentially thousands-of-entries) string on every painted
        // cell. Rebuilt from _paintingCode whenever the grid is (re)populated, and joined
        // back into _paintingCode only once, at the end of a stroke.
        private string[] _segments = Array.Empty<string>();

        private string _artist = string.Empty;
        private string _signature = string.Empty;

        private string? _autoSelected;
        private string? _selected;
        private Color _color = Color.Black;

        private const int ButtonSize = 30; // Size of each button (width and height)

        public event Action<Color>? OnColorSelected;
        public event Action<string>? OnSelected;
        public event Action<string>? OnFinalize;
        public event Action<string>? OnSignature;
        public event Action<int>? OnResizeHeight;
        public event Action<int>? OnResizeWidth;



        public CanvasWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _spriteSystem = _entManager.System<SpriteSystem>();
            Search.OnTextChanged += SearchChanged;
            //ColorSelector.OnColorChanged += SelectColor;
            ImportButton.OnPressed += _ =>
            {
                string inputCode = Search.Text.Trim();

                // Ensure the input code is not empty
                if (!string.IsNullOrEmpty(inputCode))
                {
                    _paintingCode = inputCode;

                    // Populate the grid with the new painting code
                    PopulatePaintingGrid();
                    _paintingCode = string.Join(";", _segments);
                    OnSelected?.Invoke(_paintingCode);
                }
                else
                {
                    // Optionally, show an error message
                    Search.Text = "Invalid Code";
                }
            };

            ExportButton.OnPressed += _ =>
            {
                Search.Text = _paintingCode;
                FixPaintingCode();
                PopulatePaintingGrid();
            };

            HeightSize.OnReleased += _ =>
            {
                SetHeight((int) HeightSize.Value);
                HeightSizeLabel.Text = _height.ToString();
                OnResizeHeight?.Invoke(_height);
                PopulatePaintingGrid();
            };

            HeightSize.OnValueChanged += _ =>
            {
                HeightSizeLabel.Text = HeightSize.Value.ToString();
            };

            WidthSize.OnReleased += _ =>
            {
                SetWidth((int) WidthSize.Value);
                WidthSizeLabel.Text = _width.ToString();
                OnResizeWidth?.Invoke(_width);
                PopulatePaintingGrid();
            };
            WidthSize.OnValueChanged += _ =>
            {
                WidthSizeLabel.Text = WidthSize.Value.ToString();
            };

            FinalizeButton.OnPressed += _ =>
            {
                var signature = ArtistSignature.Text.Trim();
                _artist = string.IsNullOrEmpty(signature)
                    ? Loc.GetString("canvas-artist-anonymous")
                    : signature;
                OnFinalize?.Invoke(_artist);
            };

            ArtistSignature.OnTextEntered += _ =>
            {
                _signature = ArtistSignature.Text;
                OnSignature?.Invoke(_signature);
            };
            //FixPaintingCode();
            //PopulatePaintingGrid();
        }

        private void SelectColor(Color color)
        {
            _color = color;

            OnColorSelected?.Invoke(color);
            //RefreshList();
        }

        private void SearchChanged(LineEdit.LineEditEventArgs obj)
        {
            //_autoSelected = ""; // Placeholder to kick off the auto-select in refreshlist()
            //RefreshList();
        }

        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (CanvasBoundUserInterfaceState) state;
            _selected = castState.Selected;
            // The colour palette is a fixed client-side tool for free painting, so it
            // should always be visible instead of being gated on SelectableColor.
            ColorSelector.Visible = true;
            _color = castState.Color;
            _paintingCode = castState.PaintingCode;
            _height = castState.Height;
            _width = castState.Width;
            _artist = castState.Artist;
            //Logger.ErrorS("canvas", $"received update {_paintingCode}.");

            PopulatePaintingGrid();
        }
        public void AdvanceState(string drawn)
        {
            //var filter = Search.Text;
            //if (!filter.Contains(',') || !filter.Contains(drawn))
            //    return;

            //var first = filter[..filter.IndexOf(',')].Trim();

            //if (first.Equals(drawn, StringComparison.InvariantCultureIgnoreCase))
            //{
            //    Search.Text = filter[(filter.IndexOf(',') + 1)..].Trim();
            //    _autoSelected = first;
            //}

            //RefreshList();
        }

        private void HandleColorSelected(Color color)
        {
            _color = color; // Update the current selected color
            ColorPreview.ModulateSelfOverride = color;
            OnColorSelected?.Invoke(color); // Trigger the event for external handlers
        }

        public void PopulateColorSelector(List<Color> colors)
        {
            // Clear existing children in ColorSelector
            ColorSelector.RemoveAllChildren();

            // Create a new BoxContainer for each set of 10 colors
            BoxContainer? colorGroup = null;
            int colorCount = 0;

            foreach (var color in colors)
            {
                // Create a new BoxContainer every 10 colors
                if (colorCount % 16 == 0)
                {
                    // If colorGroup already exists, add it to the ColorSelector before starting a new one
                    if (colorGroup != null)
                    {
                        ColorSelector.AddChild(colorGroup);
                    }

                    // Create a new BoxContainer for the next 10 colors
                    colorGroup = new BoxContainer
                    {
                        Orientation = LayoutOrientation.Vertical,
                    };
                }

                // Create a button for each color
                var colorButton = new Button
                {
                    MinSize = new Vector2(ButtonSize, ButtonSize),
                    MaxSize = new Vector2(ButtonSize, ButtonSize),
                    ModulateSelfOverride = color, // Set the button background to the color
                };

                // Attach an event to handle color selection
                colorButton.OnPressed += _ => HandleColorSelected(color);

                // Add the color button to the current BoxContainer (group)
                if (colorGroup != null)
                    colorGroup.AddChild(colorButton);

                colorCount++;
            }

            // Add the last group if it contains any colors
            if (colorGroup != null && colorGroup.ChildCount > 0)
            {
                ColorSelector.AddChild(colorGroup);
            }

            // Add a button specifically for transparency
            var transparencyButton = new Button
            {
                Text = Loc.GetString("canvas-window-eraser-button"),
                MinHeight = 30,
                VerticalAlignment = Control.VAlignment.Top
            };

            // Attach an event to handle transparency selection
            transparencyButton.OnPressed += _ => HandleColorSelected(Color.Transparent);

            // Add the transparency button to the ColorSelector
            ResolutionContainer.AddChild(transparencyButton);
        }


        public void SetOwner(EntityUid owner)
        {
            _owner = owner;
        }
        public void SetPaintingCode(string code)
        {
            _paintingCode = code;
        }
        public void SetArtist(string artist)
        {
            _artist = artist;
        }
        public void SetSignature(string signature)
        {
            _signature = signature;
            ArtistSignature.Text = _signature;
        }
        public void SetHeight(int height)
        {
            _height = height;
            HeightSize.Value = height;
        }
        public void SetWidth(int width)
        {
            _width = width;
            WidthSize.Value = width;
        }
        public void PopulatePaintingGrid()
        {
            // Clear any existing children in the Grids container
            Grids.RemoveAllChildren();

            if (!string.IsNullOrEmpty(_artist))
            {
                ResolutionContainer.Visible = false;
                HeaderColorPreview.Visible = false;
                HeaderTools.Visible = false;
                ArtistLabel.Text = Loc.GetString("canvas-window-artist-label", ("artist", _artist));
                ArtistLabel.Visible = true;
            }
            else
            {
                ArtistLabel.Visible = false;
            }

            int index = 0;
            bool isDrawing = false;
            bool pendingSend = false;

            RebuildSegments();

            Grids.Columns = _width;

            for (int row = 0; row < _height; row++)
            {
                int currentRow = row;

                for (int col = 0; col < _width; col++)
                {
                    int currentCol = col;

                    Color initialColor = index < _segments.Length
                        ? GetColorFromCode(_segments[index])
                        : Color.White;
                    index++;

                    var button = new Button
                    {
                        MinSize = new Vector2(ButtonSize, ButtonSize),
                        MaxSize = new Vector2(ButtonSize, ButtonSize),
                        StyleClasses = { "OpenBoth" },
                        ModulateSelfOverride = initialColor
                    };

                    button.OnButtonDown += _ =>
                    {
                        isDrawing = true;
                        button.ModulateSelfOverride = _color;
                        if (UpdatePaintingCode(currentRow, currentCol, _color))
                            pendingSend = true;
                    };

                    button.OnMouseEntered += _ =>
                    {
                        if (isDrawing)
                        {
                            button.ModulateSelfOverride = _color;
                            if (UpdatePaintingCode(currentRow, currentCol, _color))
                                pendingSend = true;
                        }
                    };

                    button.OnButtonUp += _ =>
                    {
                        isDrawing = false;
                        if (pendingSend)
                        {
                            pendingSend = false;
                            _paintingCode = string.Join(";", _segments);
                            OnSelected?.Invoke(_paintingCode);
                        }
                    };

                    Grids.AddChild(button);
                }
            }
        }



        /// <summary>
        /// Rebuilds <see cref="_segments"/> from <see cref="_paintingCode"/>, padded with white
        /// to exactly width*height entries so cell indices are always in bounds.
        /// </summary>
        private void RebuildSegments()
        {
            var required = _width * _height;
            var parsed = _paintingCode.Split(';', StringSplitOptions.RemoveEmptyEntries);
            var white = $"{Color.White.R:F2}|{Color.White.G:F2}|{Color.White.B:F2}|{Color.White.A:F2}";

            _segments = new string[required];
            for (var i = 0; i < required; i++)
                _segments[i] = i < parsed.Length ? parsed[i] : white;
        }

        /// <summary>
        /// Updates a single cell in the cached segment array. Does NOT rebuild the code string
        /// or send anything; the caller joins and sends once at the end of a stroke.
        /// </summary>
        /// <returns>True if the cell actually changed.</returns>
        private bool UpdatePaintingCode(int row, int col, Color color)
        {
            if (!string.IsNullOrEmpty(_artist))
                return false;

            // Guard against a desync between the grid size and the cached segments.
            if (_segments.Length != _width * _height)
                RebuildSegments();

            int index = row * _width + col;

            if (index < 0 || index >= _segments.Length)
            {
                Logger.ErrorS("canvas", $"Index {index} is out of bounds for painting code.");
                return false;
            }

            var newSegment = $"{color.R:F2}|{color.G:F2}|{color.B:F2}|{color.A:F2}";
            if (_segments[index] == newSegment)
                return false; // Nothing changed, skip.

            _segments[index] = newSegment;
            return true;
        }

        /// <summary>
        /// Converts a color code character to a Color object.
        /// </summary>
        private Color GetColorFromCode(string colorCode)
        {
            colorCode = new string(colorCode
                .Where(c => !char.IsWhiteSpace(c) && !char.IsControl(c))
                .ToArray());

            colorCode = colorCode.Replace(',', '.');
            string[] components = colorCode.Split('|');
            var culture = CultureInfo.InvariantCulture;
            if (components.Length == 4 &&
                float.TryParse(components[0], NumberStyles.Float, culture, out float r) &&
                float.TryParse(components[1], NumberStyles.Float, culture, out float g) &&
                float.TryParse(components[2], NumberStyles.Float, culture, out float b) &&
                float.TryParse(components[3], NumberStyles.Float, culture, out float a))
            {
                //Logger.ErrorS("canvas", $"color {colorCode} color code, color: {r}{g}{b}{a}.");
                return new Color(r, g, b, a);
            }
            Logger.ErrorS("canvas", $"color {colorCode} color code fail.");
            return Color.White; // Default to white if parsing fails
        }


        public void InitializeFromYaml(string paintingCode)
        {
            if (!string.IsNullOrEmpty(paintingCode))
            {
                _paintingCode = paintingCode;
            }

            //PopulatePaintingGrid();
        }
        private void FixPaintingCode()
        {
            int requiredSegments = _width * _height;

            // Split existing segments and count them
            string[] colorSegments = _paintingCode.Split(';', StringSplitOptions.RemoveEmptyEntries);

            if (colorSegments.Length < requiredSegments)
            {
                // Add default colors (white) for missing segments
                Color color = Color.White;
                var defaultColor = $"{color.R:F2}|{color.G:F2}|{color.B:F2}|{color.A:F2}";
                var paddedSegments = colorSegments.ToList();

                while (paddedSegments.Count < requiredSegments)
                {
                    paddedSegments.Add(defaultColor);
                }

                _paintingCode = string.Join(";", paddedSegments);
            }
        }


    }
}
